### ISSUE TITLE
ハートマークが複数出てしまう注記があります。

### ISSUE THREAD

**Issue by ptobdgithub** [happy-se-life/like#1]
プラグインをRedmineVersion4.1にインストールしたところ、
ハートマークが複数出てしまう注記があります。（出るものと出ないものの法則性が分からず...）
解決方法をご教示頂けないでしょうか？

ちなみに、インストール時に以下エラーが出ました。
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
class CreateLikes < ActiveRecord::Migration[4.2]

そのため以下ステップを修正しています。
001_create_likes.rb
修正前
class CreateLikes < ActiveRecord::Migration
修正後
class CreateLikes < ActiveRecord::Migration[5.2]

どうぞよろしくお願い致します。

**Comment by happy-se-life** [comment]
@ptobdgithub 
こんにちは。私も4.1をインストールして確認しました。
インストール時のエラーは、再現しました。修正をプッシュしました。
しかしながら、ハートマークが複数出てしまう現象は、再現ができませんでした。
もし可能でしたら、次回の再現時に、スクリーンショットとウェブページのソースを取得いただけないでしょうか。
こちらにアップいただくか、機密情報を含むようでしたら私に直接メールで提供をお願いします。
メールアドレスは、管理＞プラグインページで確認できます。
お手数をおかけしますが、よろしくお願いいたします。

**Comment by happy-se-life** [comment]
@ptobdgithub 
スクショのご提供ありがとうございました。
お陰様で、おおよその原因が判明しました。
Redmineのバージョンが4.1になった際に、注記部分がタブ化されており、
その影響で不具合になっている模様です。
＃プラグイン開発時点では4.1を使っておりませんでした。
私の手元の開発環境でも、再現ができましたので、解析・修正が可能かと思います。
解析ができましたら、修正時期をお知らせいたします。
よろしくお願いいたします。

**Comment by ptobdgithub** [comment]
@happy-se-life 
ありがとうございます！こんなに早くご対応頂けて、感謝します。
タブ化が原因だったんですね。
スクショが役に立ちなによりです。また何かお役に立てることがあればご連絡ください。
よろしくお願いいたします。

＃githubに初めてissueを書き込んで、かなり緊張しておりました。

**Comment by happy-se-life** [comment]
こんばんは😀

1) ハートマークが複数出てしまう問題を修正してpushしました。

2) 6種類のアイコンの選択方法
 redmine/plugins/like/app/models/like_constants.rb ファイルを編集してください。
 `class LikeConstants
    #
    # Choose an icon design
    # "icon_heart"
    # "icon_heart_shadow"
    # "icon_star"
    # "icon_star_shadow"
    # "icon_thumbsup"
    # "icon_thumbsup_shadow"
    #
    ICON_DESIGN = "icon_heart"
 end`

3) 「誰がいいね、したのか見れるといい」ご要望の件
 別途 Issues を起票いただけますと幸いです。

よろしくお願いします😀

**Comment by ptobdgithub** [comment]
修正対応、6種類のアイコン選択方法もありがとうございます。
インストールし直したのですが、25秒くらい「ロード中」になり、ハートマークがカウントされない状況です・・
production.logをみたところ、以下のようなログが出ていました。
何か関係あるでしょうか？

I, [2021-03-22T08:47:37.555333 #13148]  INFO -- : Started POST "/redmine/issues/update_like" for 127.0.0.1 at 2021-03-22 08:47:37 +0900
I, [2021-03-22T08:47:37.556178 #13148]  INFO -- : Processing by LikeController#update_like as JSON
I, [2021-03-22T08:47:37.556334 #13148]  INFO -- :   Parameters: {"like_id"=>"203453", "like_type"=>"journal"}
I, [2021-03-22T08:47:37.562267 #13148]  INFO -- :   Current user: (id=7)
I, [2021-03-22T08:47:37.566989 #13148]  INFO -- : Completed 200 OK in 10ms (Views: 0.2ms | ActiveRecord: 6.0ms)
I, [2021-03-22T08:47:42.165343 #13792]  INFO -- : Started POST "/redmine/issues/update_like" for 127.0.0.1 at 2021-03-22 08:47:42 +0900
I, [2021-03-22T08:47:42.166684 #13792]  INFO -- : Processing by LikeController#update_like as JSON
I, [2021-03-22T08:47:42.166953 #13792]  INFO -- :   Parameters: {"like_id"=>"203275", "like_type"=>"journal"}
I, [2021-03-22T08:47:42.175741 #13792]  INFO -- :   Current user:  (id=7)
I, [2021-03-22T08:47:42.183180 #13792]  INFO -- : Completed 200 OK in 16ms (Views: 0.3ms | ActiveRecord: 8.3ms)
I, [2021-03-22T08:47:45.523903 #13148]  INFO -- : Started POST "/redmine/issues/update_like" for 127.0.0.1 at 2021-03-22 08:47:45 +0900
I, [2021-03-22T08:47:45.524730 #13148]  INFO -- : Processing by LikeController#update_like as JSON
I, [2021-03-22T08:47:45.524934 #13148]  INFO -- :   Parameters: {"like_id"=>"203453", "like_type"=>"journal"}
I, [2021-03-22T08:47:45.530906 #13148]  INFO -- :   Current user:  (id=7)
I, [2021-03-22T08:47:45.541385 #13148]  INFO -- :   Rendering plugins/like/app/views/like_mailer/on_like.text.erb within layouts/mailer
I, [2021-03-22T08:47:45.541659 #13148]  INFO -- :   Rendered plugins/like/app/views/like_mailer/on_like.text.erb within layouts/mailer (0.0ms)
I, [2021-03-22T08:47:45.542490 #13148]  INFO -- :   Rendering plugins/like/app/views/like_mailer/on_like.html.erb within layouts/mailer
I, [2021-03-22T08:47:45.542714 #13148]  INFO -- :   Rendered plugins/like/app/views/like_mailer/on_like.html.erb within layouts/mailer (0.0ms)
E, [2021-03-22T08:48:45.601371 #13148] ERROR -- : Email delivery error: Net::ReadTimeout
I, [2021-03-22T08:48:45.602402 #13148]  INFO -- : Completed 200 OK in 60077ms (Views: 0.4ms | ActiveRecord: 7.4ms)

**Comment by happy-se-life** [comment]
いいねすると「あなたにいいねが届きました」的な、通知メールが送信されます。
ログを拝見すると通知メールの送信がエラーになり、タイムアウトになっています。
Redmineのメールサーバーの設定は正しく行われていますか？

**Comment by ptobdgithub** [comment]
なるほど、メールが届く設定になっているんですね。
（テスト端末で検証しているのでメール機能をonにできない状態です）

私どものRedmineユーザーたちはメール通知を嫌がるかもしれません・・（今の段階でも多いと嫌がられています）
メール通知をoffにするやり方を、教えて頂けないでしょうか。

**Comment by happy-se-life** [comment]
冷静に考えると今どきメール通知とか古過ぎますよねえ😀
like_constants.rb にメール通知をオフにするフラグを追加しましたので、ご確認ください。
よろしくお願いします😀

**Comment by ptobdgithub** [comment]
like_constants.rb に以下ロジックを追加して再起動したのですが、logをみるとメール機能が動いてしまうようで・・
他に直すところ、ありますでしょうか？
よろしくお願いいたします。（すみません、色々初心者です）

#
# Constant definition
#
class LikeConstants
    #
    # Choose an icon design
    # "icon_heart"
    # "icon_heart_shadow"
    # "icon_star"
    # "icon_star_shadow"
    # "icon_thumbsup"
    # "icon_thumbsup_shadow"
    #
    ICON_DESIGN = "icon_heart"
    # Enable mail notification (1:on 0:off)
    ENABLE_MAIL_NOTIFICATION = 0
end



I, [2021-03-22T11:46:14.609872 #5396]  INFO -- : Processing by LikeController#update_like as JSON
I, [2021-03-22T11:46:14.610036 #5396]  INFO -- :   Parameters: {"like_id"=>"203528", "like_type"=>"journal"}
I, [2021-03-22T11:46:14.626918 #5396]  INFO -- :   Current user: TK098398 (id=7)
I, [2021-03-22T11:46:17.374101 #5396]  INFO -- :   Rendering plugins/like/app/views/like_mailer/on_like.text.erb within layouts/mailer
I, [2021-03-22T11:46:17.374767 #5396]  INFO -- :   Rendered plugins/like/app/views/like_mailer/on_like.text.erb within layouts/mailer (0.4ms)
I, [2021-03-22T11:46:20.111355 #5396]  INFO -- :   Rendering plugins/like/app/views/like_mailer/on_like.html.erb within layouts/mailer
I, [2021-03-22T11:46:20.111954 #5396]  INFO -- :   Rendered plugins/like/app/views/like_mailer/on_like.html.erb within layouts/mailer (0.4ms)
E, [2021-03-22T11:47:20.229365 #5396] ERROR -- : Email delivery error: Net::ReadTimeout
I, [2021-03-22T11:47:20.230127 #5396]  INFO -- : Completed 200 OK in 65620ms (Views: 0.3ms | ActiveRecord: 21.6ms)

**Comment by happy-se-life** [comment]
こんにちは😀
今回、2つのファイルを更新していますので、両方のファイルが更新されているかどうか、ご確認くださいませ。
[https://github.com/happy-se-life/like/commit/04ecc82df0190d736f5c8e12ecc61f2b253f7f44](url)

**Comment by ptobdgithub** [comment]
commit履歴の連携ありがとうございます！
無事インストール、メール通知offになりました。

チケットが開けるものと、internal errorで落ちてしまうものがあります。
ログは以下の通りなのですが・・（別issue立てたほうがいいでしょうか）


I, [2021-03-22T13:43:34.479211 #15200]  INFO -- : Completed 500 Internal Server Error in 2810ms (ActiveRecord: 90.8ms)
F, [2021-03-22T13:43:34.479977 #15200] FATAL -- :   
F, [2021-03-22T13:43:34.480060 #15200] FATAL -- : ActionView::Template::Error (undefined method `length' for nil:NilClass):
F, [2021-03-22T13:43:34.480193 #15200] FATAL -- :     34:     <%= render_notes(issue, journal, :reply_links => reply_links) unless journal.notes.blank? %>
    35:     </div>
    36:   </div>
    37:   <%= call_hook(:view_issues_history_journal_bottom, { :journal => journal }) %>
    38: <% end %>
    39: 
    40: <% heads_for_wiki_formatter if User.current.allowed_to?(:edit_issue_notes, issue.project) || User.current.allowed_to?(:edit_own_issue_notes, issue.project) %>
F, [2021-03-22T13:43:34.480271 #15200] FATAL -- :   
F, [2021-03-22T13:43:34.480354 #15200] FATAL -- : plugins/like/lib/hooks.rb:14:in `view_issues_history_journal_bottom'
lib/redmine/hook.rb:63:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `block in call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:98:in `call_hook'
app/views/issues/tabs/_history.html.erb:37:in `block in _app_views_issues_tabs__history_html_erb__196766751_131136620'
app/views/issues/tabs/_history.html.erb:7:in `each'
app/views/issues/tabs/_history.html.erb:7:in `_app_views_issues_tabs__history_html_erb__196766751_131136620'
app/views/common/_tabs.html.erb:21:in `block in _app_views_common__tabs_html_erb__1011335357_134107020'
app/views/common/_tabs.html.erb:20:in `each'
app/views/common/_tabs.html.erb:20:in `_app_views_common__tabs_html_erb__1011335357_134107020'
app/helpers/application_helper.rb:439:in `render_tabs'
app/views/issues/show.html.erb:126:in `_app_views_issues_show_html_erb__90718068_95014200'
app/controllers/issues_controller.rb:107:in `block (2 levels) in show'
app/controllers/issues_controller.rb:99:in `show'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:72:in `call'

**Comment by happy-se-life** [comment]
ご報告ありがとうございます。
ログからわかる内容で修正を加えました。
https://github.com/happy-se-life/like/commit/c46ec1ab3bccb0b6a15c8e662e4af8c2d5bcb337
すみません、機能面への影響は不明です。レポートしていただけると助かります。

**Comment by happy-se-life** [comment]
こんばんは😀
一つ前の修正方法が間違ってましたね。すみません😞
https://github.com/happy-se-life/like/commit/7cb969918a678273877b533f92ed7626a3cebe7f
これでいけると思います。

**Comment by ptobdgithub** [comment]
改修ありがとうございます！
テスト環境で問題なく動くことを確認いたしました。
早急にご対応頂いて、感謝ですm(_ _"m)

**Comment by happy-se-life** [comment]
ご確認ありがとうございました😀
