### ISSUE TITLE
誰がいいね！したか分かると嬉しいです。

### ISSUE THREAD

**Issue by sbrdiag** [happy-se-life/like#2]
現在いいね！されたカウント数が分かりますが、
誰がいいね！したか分かると、もっと嬉しいです。
（チケット作成者や注記を書いた人が、「誰が読んでいるか」が分かると、連絡を取れる手段にもなりモチベーションも上がるのかなと）

もしお時間等ありましたら、よろしくお願いいたします😀

**Comment by happy-se-life** [comment]
おはようございます😀
下記のイメージで実装しました。マウスオーバーで表示されます。
お時間のある時にテスト環境でご確認ください。
<img width="781" alt="like_tooltip_ss" src="https://user-images.githubusercontent.com/57052261/112770671-c1f22a00-9062-11eb-8b8f-97fd4e04c976.png">

**Comment by sbrdiag** [comment]
おはようございます。
早速試させて頂きました！
自分のハートマークでは名前は表示されない感じでしょうか？
（すみません、今日は業務立て込んでいて返信遅くなります💦）

**Comment by sbrdiag** [comment]
すみません！やり直したら名前が表示されました。ばっちりです。
またテスト環境変えて検証させて頂きます。
ありがとうございました(^▽^)/

**Comment by happy-se-life** [comment]
ありがとうございます😀
こちらは、急いでおりませんので、お時間の許すさいに検証ください。
Issueをクローズ可能か、またご連絡いただけましたら幸いです。

**Comment by sbrdiag** [comment]
テスト環境で複数人で確認し、本日本番環境にインストールさせて頂きました！
SNS世代にはすごく喜ばれている気がします・・
これでチケットをみるモチベーションがあがってくれたら。

本当に、機能追加して下さりありがとうございました。

**Comment by happy-se-life** [comment]
こんにちは。使っていただけて嬉しいです😀
今後ともよろしくお願いいたします！

**Comment by sbrdiag** [comment]
一日経ちましたが、ユーザーたちの感想を追記させて頂きます💦
今後ともよろしくお願いいたします。

>
注記に何か書くとメール飛ぶから
あんまり書きたくないって人とかは、見たらいいねしてくださいっていうのはめっちゃ使えると思います。
既読確認とかでも使えるし神ですね(みんなが使ってくれるかどうかはともかく)

>
これ便利ですね。
感覚的にはチェックボックスの進化版で、
全ての注記（Wikiも含むから記事？）にレスポンスできるのは発言者にとって良い気がします。

>
さっそくじゃんじゃん使ってます～

>
さりげない応援感がいいですね

**Comment by happy-se-life** [comment]
フィードバックありがとうございます！😀
とても嬉しいです。開発の励みになります。
