### ISSUE TITLE
Delete other persons Like (Admin user)

### ISSUE THREAD

**Issue by rm-plugin-lurker** [happy-se-life/like#4]
Hello.

In current implementation of the tool, is there a way for admin user to remove Like of other users?

**Comment by happy-se-life** [comment]
Hello,

There is no way to remove it in the current implementation. If you really want to delete it, you can do it by manipulating the database directly using SQL.

**Comment by rm-plugin-lurker** [comment]
Ok thank you. I will now close the ticket.
